#!/usr/bin/with-contenv sh

echo -------------------------------------
echo           _     _ _
echo         | |___| (_) ___
echo         | / __| | |/ _ \ 
echo         | \__ \ | | (_) |
echo         |_|___/ |_|\___/
echo               |_|
echo Brought to you by linuxserver.io
echo We gratefully accept donations at:
echo https://www.linuxserver.io/index.php/donations/
echo -------------------------------------
echo GID/UID
echo -------------------------------------
echo User uid:    501
echo User gid:    501
echo -------------------------------------